version: 2

models:
  - name: orders
    columns:
      - name: number_of_orders
        tests:
        - dbt_utils.expression_is_true:
            expression: "number_of_orders > -1"



   