version: 2

models:
  - name: orders
    columns:
      - name: customer_id
        tests:
          - not_null
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
      - name: number_of_orders
        tests:
          - accepted_values:
              values: [0, 1, 2, 3, 5]