version: 2

models:
  - name: orders
    columns:
        - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'returned','return_pending']