version: 2

models:
  - name: medicaresummary
    columns:
      - name: provider_id
        tests:
          - not_null
          - unique
      - name: provider_state
        tests:
        - accepted_values:
          values: ['MA',
'RI',
'NH',
'ME',
'VT',
'CT',
'NJ',
'NY',
'PA',
'DE',
'DC',
'VA',
'MD',
'WV',
'NC',
'SC',
'GA',
'FL',
'AL',
'TN',
'MS',
'KY',
'OH',
'IN',
'MI',
'IA',
'WI',
'MN',
'SD',
'ND',
'MT',
'IL',
'MO',
'KS',
'NE',
'LA',
'AR',
'OK',
'TX',
'CO',
'WY',
'ID',
'UT',
'AZ',
'NM',
'NV',
'CA',
'HI',
'OR',
'WA',
'AK']
